### ISSUE TITLE
Remove the concept of "purchase token" and just use the Purchase object?

### ISSUE THREAD

**Issue by mgiuca** [WICG/digital-goods#22]
The only use of the "purchase token" is to get it out of the `Purchase` object and pass it as an argument to `acknowledge`.

Instead, it would be more straightforward (avoiding the indirection of the token) to just have `acknowledge` directly take a `Purchase` object, or better still, move `acknowledge` to a method of `Purchase` (that's the "correct" object oriented design).

I think this is an instance where the Play Billing API design leaked into the Web API design. We looked at the Windows Store API and it does not have a "purchase token"; you just directly acknowledge the Purchase object. So it would be difficult (though not impossible) to map the current API onto the Windows API.

**Comment by phoglenix** [comment]
Closing as we have now moved in a different direction for DGAPI v2.0: it is better to include a token here because it can be passed through to other more trustable (ie. not client-side) APIs for verification, which we recommend to prevent potential fraud.
