### ISSUE TITLE
Consider using DOMHighResTimestamp instead of DOMTimeStamp

### ISSUE THREAD

**Issue by yoavweiss** [WICG/digital-goods#32]
We're considering our options RE `DOMTimeStamp`, and wondering what it's used for. It seems less well-defined than `DOMHighResTimestamp`. Would y'all consider switching over?

See https://github.com/heycam/webidl/issues/2 for discussion.

**Comment by phoglenix** [comment]
Yes. We don't actually need high precision (we would be happy with a Date with its predefined epoch) but if IDL switches to prefer DOMHighResTimestamp we could switch over.

**Comment by yoavweiss** [comment]
Thanks!!
