### ISSUE TITLE
Make makeAvailableAgain a mandatory enum, rather than an optional bool

### ISSUE THREAD

**Issue by mgiuca** [WICG/digital-goods#4]
Current design:

```webidl
Promise<void> acknowledge(PurchaseToken purchaseToken,
                          optional AcknowledgeParams params = {});

dictionary AcknowledgeParams {
  boolean makeAvailableAgain = true;
};
```

I think having mandatory Boolean parameters is bad design, which is why I made it optional and moved it into a params dictionary. So it should either be:

- An optional Boolean (as above), or
- A mandatory enum (making the values explicit).

Glen convinced me that it's more important in this case that the client is forced to make a decision about whether to make the purchase available again in the future, rather than having either option be the default, so it should be mandatory. That means it should be an enum, with values like (strawman): {`"repurchasable"`, `"permanent"`}.

**Comment by phoglenix** [comment]
How about
enum PurchaseType { "repeatable", "permanent" }

**Comment by mgiuca** [comment]
`repeatable` good. Since we're no longer using the term "`onetime`" in the ItemType (#3), I propose s/`permanent`/`onetime`.

**Comment by phoglenix** [comment]
Sounds good to me.

**Comment by phoglenix** [comment]
Actually, seeing as #3 is still open (we might add ItemType { 'onetime' } in future) maybe we should avoid PurchaseType ('onetime') because it is similar and so potentially confusing?

**Comment by mgiuca** [comment]
I expect we have an answer for #3 even though it's still open. "onetime" makes more sense to me for this concept (a purchase that you can only make once and then it's permanently in your account), than what we were using it for previously (a purchase that you can make many times, but isn't automatically renewing).

**Comment by phoglenix** [comment]
Ok, sounds good again.
