### ISSUE TITLE
getDigitalGoodsService("https://play.google.com/billing") always returning “DOMException: unsupported context” error

### ISSUE THREAD

**Issue by azabraao** [WICG/digital-goods#42]
I have [a working TWA on Play Store][1]  ([website reference][2]) that I’m trying to update for enabling it to handle google play digital goods payments. I’ve already implemented an in-app purchase using stripe. When I submitted a simple update to the app play store images it got rejected because they noticed the missing google in-app purchase that I didn’t know yet that was required. So I’m working now on implementing it.

**What I’ve made:**

1. Updated my twa-manifest.json to include billing permissions. As the first step [on this article by google][3]:

```
  ...
  "enableNotifications": true,
  "features": {
    "playBilling": {
      "enabled": true
    }   
  },  
  "alphaDependencies": {
    "enabled": true
  },
  ...
```

 2. As I use Android Studio and not Bubblewrapp to build my app, I went to [this other tutorial article][4] And followed every step in it: (a) update build gradle, sync it. (b) Create DelegationService.java and reference it on AndroidManifest.xml (c) Added the service and the activity recommended by them, also to AndroidManifest.xml.

 3. I made the app signed bundle release build  and for quick testing, I’ve uploaded it to the [play store internal testing][5]  

**The problem:**

I’ve used this generated testing link to download and install the new release on two devices: a Pixel 2 (Api 30) Emulator, and a  Redmi Note 8 and as my target is to implement the play store digital goods api, I inspected the app from chrome://inspect/#devices and noticed that getDigitalGoodsService is enabled but fails when getting the Google Play Billing service:

```
if('getDigitalGoodsService' in window) {
	const service = await getDigitalGoodsService("https://play.google.com/billing")
}
````

Which the getDigitalGoodsService fails with the error: 

<img width="679" alt="getbigitalGoodsService(httpsplay-google combilling)" src="https://user-images.githubusercontent.com/17601387/153536668-48a63197-d7a5-46fc-a0e4-8e1b72075275.png">

My hypothesis is that it isn’t working because the app is download from a testing link and not as a Play Store approved release. 

Also, the URL bar is showing. But again my hypothesis to it is the same as above because I’ve made 0 changes to the digital asset links configuration that in the current production release is working fine on users' devices. But I wonder if this fact should give some explanation on why the getDigitalGoodsService fails. 

<img width="406" alt="bibleplan online" src="https://user-images.githubusercontent.com/17601387/153536701-837cc70f-cd0c-4c74-bb91-d0d67b2b6e8f.png">

Anyway, I hope I’m wrong on my hypothesis because it would mean that first I would need to release a version with the billing permissions which would be rejected because they will not see the implementation of google play billing, which is required to in-app purchases implementations. So as I don’t have an approved TWA release to debug and implement the billing, I would be stuck on the process. Unless of course, I’ve not yet noticed another way to solve it. 

Any suggestions?

  [1]: https://play.google.com/store/apps/details?id=xyz.appmaker.ybhmxs
  [2]: https://bibleplan.online
  [3]: https://developer.chrome.com/docs/android/trusted-web-activity/receive-payments-play-billing/
  [4]: https://developer.chrome.com/docs/android/trusted-web-activity/play-billing/
  [5]: https://play.google.com/console/internal-app-sharing
  [6]: https://i.stack.imgur.com/li7Qi.png

**Comment by phoglenix** [comment]
The URL bar showing is an indication that you are not in scope of the TWA (perhaps you haven't declared your origin correctly or signed using Digital Asset Links correctly?), which would be an unsupported context.
I'm not actually familiar with the TWA/Bubblewrap configuration. You may be better off filing bugs on the documentation sites that tell you how to set them up for DGAPI.

**Comment by azabraao** [comment]
I was sure I had made the digital asset links configuration correctly, but you are right! I've made a better read on [this doc](https://developer.chrome.com/docs/android/trusted-web-activity/android-for-web-devs/#digital-asset-links) and discovered that I didn't know that each release might have its own SHA 256 fingerprint and I could get it with the [Asset Links Tool from Play Store.](https://play.google.com/store/apps/details?id=dev.conn.assetlinkstool&hl=en&gl=US) 

Thank you so much @phoglenix 🎉

For those who might hit here in the future. Remember to, using this Asset Links app verify the SHA 256 link, find and take your app configuration, and append it to your production assetlinks.json (on example.com/.well-known/assetlinks.json): 

```
[
// ...your previous configuration
  {
    "relation": ["delegate_permission/common.handle_all_urls"],
    "target": {
      // your current testing asset links fingerprint took from the Asset Links app
    }
  }
]

```
