### ISSUE TITLE
Define the relationship of getDetails output array to the input list

### ISSUE THREAD

**Issue by mgiuca** [WICG/digital-goods#6]
And answer what happens if one of the input itemIds is not found.

Does it:

- Return an array with a 1:1 mapping of indices to the input list (this would require that missing IDs generate nulls in the output array, rather than being omitted).
- Return an array without an explicit guarantee like that (missing IDs would be omitted from the output). This is preferred, but note that it could encourage developers to _think_ that the output indices match the input indices, since that will almost always be the case.
- Return an array sorted by itemId (so the indices to not match).

@phoglenix

**Comment by phoglenix** [comment]
I think that explicitly **not** guaranteeing the return order is the best solution here. Just document it clearly on the method.
If we're really worried about it then some unspecified shuffling of the order shouldn't be difficult.

**Comment by mgiuca** [comment]
Also a potential consideration of one ID returning multiple items. This could happen on the Play Store backend if (and we're not sure if this is possible) you are allowed to have the same ID representing a one-time item and a subscription.

Since we're dropping the ItemType (#3), that means we could potentially surface 2 results for a single-ID query. Need to decide whether to arbitrarily drop one, or return both. (I am in favour of dropping one, if this actually is a thing that can happen.)
